version: '3'
services:
  luke_web:
    container_name: luke-web
    build: ./
    hostname: web
    ports:
      - "8000:8000"
    volumes:
      - /home/ubuntu/tick.log:/app/tick.log
    env_file:
      - "envfile"
networks:
  default:
    external:
      name: websites
